name: issue_closed
on:
  issues:
    types:
      - closed

jobs:
  build:
    name: Execute
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Zone Link - Board
        DISCORD_AVATAR: https://zonelink.net/github_board.png
        DISCORD_EMBEDS: '[{"title":"Task Completed - ${{github.event.issue.title}}", "color": 5763719, "url": "${{github.event.issue.html_url}}" }]'
      uses: Ilshidur/action-discord@master
