name: issue_created
on:
  issues:
    types:
      - opened

jobs:
  build:
    name: Execute
    runs-on: ubuntu-latest
    steps:
    - name: Compute variables
      id: var1
      run: echo ::set-output name=issue_title::'`[${{github.event.issue.title}}](${{github.event.issue.html_url}})`'
    - name: Compute issue_body
      id: var2
      run: echo ::set-output name=issue_title::toJSON(github.event.issue.body)
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Zone Link - Board
        DISCORD_AVATAR: https://zonelink.net/github_board.png
        DISCORD_EMBEDS: '[{"title":"Task Created", "color": 0, "description": "${{steps.var1.outputs.issue_title}}\n${{steps.var2.outputs.issue_body}}" }]'
      uses: Ilshidur/action-discord@master
