name: issue_created
on:
  issues:
    types:
      - opened

jobs:
  build:
    name: Execute
    runs-on: ubuntu-latest
    steps:
    - name: Set ISSUE_BODY
      run: echo "ISSUE_BODY=${{toJSON(github.event.issue.body)}}" >> $GITHUB_ENV
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Zone Link - Board
        DISCORD_AVATAR: https://zonelink.net/github_board.png
        DISCORD_EMBEDS: '[{"title":"Task Created", "color": 0, "description": "**` [${{github.event.issue.title}}](${{github.event.issue.html_url}}) `**\n\n``` ${{env.ISSUE_BODY}} ```" }]'
      uses: Ilshidur/action-discord@master
